# Site settings
title: Weeno Ridge LLC
email: andrewgeorge47@gmail.com
description: >-
  Weeno Ridge LLC is the parent company for several interconnected initiatives 
  that combine science engagement, community development, and personal growth.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://weenoridge.com" # your domain

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
