# Site settings
title: Weeno Ridge LLC
email: contact@weeno-ridge.com
description: >-
  Weeno Ridge LLC is the parent company for several interconnected initiatives 
  that combine science engagement, community development, and personal growth.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://weenoridge.com" # your domain
github_username: andrewgeorge47

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
header_pages:
  - measured.md
  - neighborhood.md
  - golfos.md
  - about.md
  - contact.md
